# Generated by Django 5.2 on 2025-04-22 14:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlashNotice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('image', models.ImageField(upload_to='flash_notices/')),
                ('trun_flash_On', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'flash_notice',
            },
        ),
        migrations.CreateModel(
            name='GalleryAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('coverPhoto', models.ImageField(upload_to='gallery/cover/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])])),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'gallery_album',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='ManagementCommittee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('position', models.CharField(choices=[('Chairman', 'Chairman'), ('Secretary', 'Secretary'), ('Member', 'Member')], max_length=50)),
                ('contact_no', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='committee_images/')),
                ('site_position', models.IntegerField(choices=[(0, 'Chairman'), (1, 'Secretary'), (2, 'Member - 1st'), (3, 'Member - 2nd'), (4, 'Member - 3rd'), (5, 'Member - 4th'), (6, 'Member - 5th')], default=0)),
                ('update_by', models.CharField(default='admin', max_length=45)),
                ('committee_type', models.CharField(choices=[('Management Committee', 'Management Committee'), ('Parent Teacher Association', 'Parent Teacher Association')], default='management', max_length=50)),
            ],
            options={
                'db_table': 'management_committee',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('post', models.CharField(choices=[('Principal', 'Principal'), ('Vice Principal', 'Vice Principal'), ('Teacher', 'Teacher'), ('Instructor', 'Instructor'), ('Lab Assistant', 'Lab Assistant'), ('Nurse', 'Nurse'), ('Accountant', 'Accountant'), ('Assistant', 'Assistant'), ('Helper', 'Helper'), ('Other', 'Other')], max_length=50)),
                ('qualification', models.CharField(max_length=100)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=6, null=True)),
                ('doj', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='staff_images/')),
                ('site_position', models.IntegerField(choices=[(0, 'Principal'), (1, 'Vice Principal'), (2, 'Secondary - 1st'), (3, 'Secondary - 2nd'), (4, 'Secondary - 3rd'), (5, 'Lower - 1st'), (6, 'Lower - 2nd'), (7, 'Lower - 3rd'), (8, 'Primary - 1st'), (9, 'Primary - 2nd'), (10, 'Primary - 3rd'), (11, 'Nursery Teacher'), (12, 'Staff Nurse'), (13, 'Accountant'), (14, 'Office Assistant'), (15, 'Helpers')])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave'), ('retired', 'Retired')], default='active', max_length=10)),
                ('staff_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('update_by', models.CharField(default='admin', max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'staffs',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/photos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])])),
                ('caption', models.TextField(blank=True)),
                ('uploaded_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='main.galleryalbum')),
            ],
            options={
                'db_table': 'gallery_photos',
                'ordering': ['-uploaded_date'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='gallery/videos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'mkv', 'webm', 'flv', 'wmv', 'mpeg', 'm4v'])])),
                ('caption', models.TextField(blank=True)),
                ('uploaded_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='main.galleryalbum')),
            ],
            options={
                'db_table': 'gallery_videos',
                'ordering': ['-uploaded_date'],
            },
        ),
    ]
