# Generated by Django 5.2 on 2025-04-22 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('cover_image', models.ImageField(upload_to='event_covers/')),
                ('event_date_bs', models.CharField(help_text='Nepali (BS) Date in YYYY-MM-DD format', max_length=10)),
                ('event_date_ad', models.DateField(blank=True, editable=False, null=True)),
                ('gallery_album', models.ForeignKey(blank=True, help_text='Link to gallery album after event', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.galleryalbum')),
            ],
            options={
                'db_table': 'events',
                'ordering': ['-event_date_ad'],
            },
        ),
    ]
