# Generated by Django 5.2 on 2025-04-24 16:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_contactfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_level', models.CharField(choices=[('Nursery', 'Nursery'), ('KG', 'KG'), ('1', 'Grade 1'), ('2', 'Grade 2'), ('3', 'Grade 3'), ('4', 'Grade 4'), ('5', 'Grade 5'), ('6', 'Grade 6'), ('7', 'Grade 7'), ('8', 'Grade 8'), ('9', 'Grade 9'), ('10', 'Grade 10'), ('11', 'Grade 11'), ('12', 'Grade 12')], max_length=20, verbose_name='Class Level')),
                ('medium', models.CharField(blank=True, choices=[('English', 'English Medium'), ('Nepali', 'Nepali Medium')], max_length=20, null=True, verbose_name='Medium of Instruction')),
                ('faculty', models.CharField(blank=True, choices=[('General', 'General'), ('Engineering', 'Engineering')], max_length=20, null=True, verbose_name='Faculty')),
                ('section', models.CharField(blank=True, max_length=10, null=True, verbose_name='Section')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this grade is currently active', verbose_name='Is Active')),
                ('can_join', models.BooleanField(default=True, help_text='Whether new admissions are open for this grade', verbose_name='Can Join')),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'db_table': 'grades',
                'ordering': ['class_level', 'medium', 'faculty'],
                'unique_together': {('class_level', 'medium', 'faculty', 'section')},
            },
        ),
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10, verbose_name='Gender')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('father_name', models.CharField(blank=True, max_length=100, null=True, verbose_name="Father's Name")),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True, verbose_name="Mother's Name")),
                ('previous_school', models.CharField(blank=True, max_length=100, null=True, verbose_name='Previous School')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('intro', models.TextField(blank=True, help_text='Short introduction about yourself', null=True, verbose_name='Introduction')),
                ('image', models.ImageField(upload_to='admission_applications/%Y/', verbose_name='Passport Photo')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Application Status')),
                ('registered_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registration Date')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the application', null=True, verbose_name='Admin Notes')),
                ('grade', models.ForeignKey(limit_choices_to={'can_join': True}, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='main.grade', verbose_name='Grade Applying For')),
            ],
            options={
                'verbose_name': 'Admission Application',
                'verbose_name_plural': 'Admission Applications',
                'db_table': 'admission_applications',
                'ordering': ['-registered_on'],
            },
        ),
    ]
