# Generated by Django 5.2 on 2025-04-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_grade_admissionapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='section',
            field=models.CharField(default='A', max_length=10, verbose_name='Section'),
        ),
    ]
