# Generated by Django 5.2 on 2025-05-10 06:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_grade_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassDemographics',
            fields=[
                ('grade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='demographics', serialize=False, to='main.grade', verbose_name='Grade')),
                ('total_students', models.PositiveIntegerField(default=0, verbose_name='Total Students')),
                ('boys_count', models.PositiveIntegerField(default=0, verbose_name='Number of Boys')),
                ('girls_count', models.PositiveIntegerField(default=0, verbose_name='Number of Girls')),
                ('other_gender_count', models.PositiveIntegerField(default=0, verbose_name='Other Genders')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Class Demographics',
                'verbose_name_plural': 'Class Demographics',
            },
        ),
        migrations.CreateModel(
            name='ClassAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('boys_present', models.PositiveIntegerField(default=0, verbose_name='Boys Present')),
                ('girls_present', models.PositiveIntegerField(default=0, verbose_name='Girls Present')),
                ('other_gender_present', models.PositiveIntegerField(default=0, verbose_name='Other Genders Present')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('demographics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='main.classdemographics', verbose_name='Class Demographics')),
            ],
            options={
                'verbose_name': 'Class Attendance',
                'verbose_name_plural': 'Class Attendance Records',
                'ordering': ['-date', 'demographics'],
                'unique_together': {('demographics', 'date')},
            },
        ),
    ]
