# Generated by Django 5.2 on 2025-05-10 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_classdemographics_classattendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classdemographics',
            name='total_students',
        ),
    ]
