# Generated by Django 5.2 on 2025-05-13 05:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_publicholiday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicholiday',
            options={'ordering': ['start_date'], 'verbose_name': 'Public Holiday', 'verbose_name_plural': 'Public Holidays'},
        ),
        migrations.AlterUniqueTogether(
            name='publicholiday',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='publicholiday',
            name='end_date',
            field=models.DateField(default=datetime.date(2025, 5, 13)),
        ),
        migrations.AddField(
            model_name='publicholiday',
            name='start_date',
            field=models.DateField(default=datetime.date(2025, 5, 13)),
        ),
        migrations.AlterField(
            model_name='publicholiday',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='If true, this holiday recurs annually from start_date to end_date.'),
        ),
        migrations.RemoveField(
            model_name='publicholiday',
            name='date',
        ),
    ]
