# Generated by Django 5.2 on 2025-05-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_publicholiday_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicholiday',
            name='publsihed',
            field=models.BooleanField(default=False, help_text='If true, this holiday is published and visible to users.'),
        ),
    ]
