# Generated by Django 5.2 on 2025-05-13 09:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_publicholiday_publsihed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicholiday',
            old_name='publsihed',
            new_name='published',
        ),
        migrations.AlterField(
            model_name='publicholiday',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='publicholiday',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='If true, this holiday occurs every year but may have different dates (needs annual update)'),
        ),
        migrations.AlterField(
            model_name='publicholiday',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
