# Generated by Django 5.2 on 2025-05-14 05:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rename_publsihed_publicholiday_published_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceAccessLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Description of this link', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('access_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Attendance Access Link',
                'verbose_name_plural': 'Attendance Access Links',
            },
        ),
    ]
