# Generated by Django 5.2 on 2025-05-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_attendanceaccesslink'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAttendanceSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_staff', models.PositiveIntegerField()),
                ('active_staff', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Staff Attendance Summary',
                'verbose_name_plural': 'Staff Attendance Summaries',
                'ordering': ['-date'],
            },
        ),
    ]
