# Generated by Django 5.2 on 2025-05-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_staffattendancesummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceaccesslink',
            name='available_from',
            field=models.TimeField(blank=True, help_text='Time of day when the link becomes valid', null=True),
        ),
        migrations.AddField(
            model_name='attendanceaccesslink',
            name='available_until',
            field=models.TimeField(blank=True, help_text='Time of day when the link becomes invalid', null=True),
        ),
    ]
